### ISSUE TITLE
Will this work with Varnish 4/5?

### ISSUE THREAD

**Issue by pantaoran** [willemk/varnish-mobiletranslate#9]
The doc says `Varnish 3 is a requirement`. That statement seems outdated since Varnish 4 came out in 2014 and Varnish 5 came out in 2016. What's the compatibility situation?

**Comment by drorsnir** [comment]
Seems to work just fine with my Varnish 5. Also worked with Varnish 4 before it.

**Comment by eerootsus** [comment]
Yes - I'm using this for 3, 4 and 5. It basically just generates custom regex and if statements, so nothing special.
